server:
  port: 9095
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379