server:
  port: 8085
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration